/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes.GUI;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JTextField;
import javax.swing.ListModel;

/**
 *
 * @author IDS CREW
 */
public class menuDosen extends javax.swing.JFrame {

    /**
     * Creates new form menuDosen
     */
    public menuDosen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        menuDosenl = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfKelas = new javax.swing.JTextField();
        btAddKelas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSelected = new javax.swing.JList<>();
        btHapusList = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btTambahList = new javax.swing.JButton();
        cbKelas2 = new javax.swing.JComboBox<>();
        btRemove = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfNamaTugas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btAddTugas = new javax.swing.JButton();
        btHapusList1 = new javax.swing.JButton();
        cbKelas = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        listSelected1 = new javax.swing.JList<>();
        btTambahList1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        listMatkul = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuDosenl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuDosenl.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel1.setText("Nama Kelas");

        btAddKelas.setText("Tambahkan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btAddKelas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(tfKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(68, 68, 68)
                .addComponent(btAddKelas)
                .addGap(35, 35, 35))
        );

        menuDosenl.addTab("Tambah Kelas", jPanel1);

        listSelected.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listSelected);

        btHapusList.setText("-");
        btHapusList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusListActionPerformed(evt);
            }
        });

        jLabel8.setText("List Kelas");

        btTambahList.setText("+");

        cbKelas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btRemove.setText("Remove");
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(cbKelas2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btHapusList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btTambahList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btRemove)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btTambahList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btHapusList))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cbKelas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRemove)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        menuDosenl.addTab("Remove Kelas", jPanel2);

        jLabel3.setText("Nama Tugas");

        jLabel4.setText("Kelas");

        btAddTugas.setText("Tambahkan");

        btHapusList1.setText("-");

        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane5.setViewportView(listSelected1);

        btTambahList1.setText("+");
        btTambahList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahList1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Mata Kuliah");

        listMatkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAddTugas)
                .addGap(120, 120, 120))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNamaTugas, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btTambahList1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btHapusList1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(listMatkul, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNamaTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(listMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTambahList1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btHapusList1))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btAddTugas)
                .addContainerGap())
        );

        menuDosenl.addTab("Tambah Tugas", jPanel4);

        jMenu1.setText("File");

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuDosenl, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuDosenl, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void btHapusListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btHapusListActionPerformed

    private void btTambahList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahList1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btTambahList1ActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRemoveActionPerformed

    public JButton getBtRemove() {
        return btRemove;
    }

    public JButton getBtnHapusList() {
        return btHapusList1;
    }

    public JButton getBtnTambahList() {
        return btTambahList1;
    }

    public JMenuItem getMenuLogout() {
        return menuLogout;
    }

    public JButton getBtnRemove() {
        return btHapusList;
    }

    public JButton getBtnAddKelas() {
        return btAddKelas;
    }

    public JButton getBtnAddTugas() {
        return btAddTugas;
    }
    
    public JButton getBtnHapus(){
        return btHapusList1;
    }

//    public JButton getBtnTambahMatkul() {
//        return tambahMatkul;
//    }
//
//    public JButton getBtnRegMatkul() {
//        return regMatkul;
//    }
    
    public void addActionListener(ActionListener e){
        this.btAddKelas.addActionListener(e);
        this.btAddTugas.addActionListener(e);
        this.btHapusList.addActionListener(e);
        this.btHapusList1.addActionListener(e);
        this.btRemove.addActionListener(e);
        this.btTambahList.addActionListener(e);
        this.btTambahList1.addActionListener(e);
        this.menuLogout.addActionListener(e);
        }
    
    
//    public String getSelectKelas1() {
//        return listKelas1.getSelectedValue();
//    }
//
//    public int getIntSKS() {
//        return (int) intSKS.getValue();
//    }
//
//    public String getSelectKelas2() {
//        return listKelas2.getSelectedValue();
//    }
//
//    public String getSelectKelas3() {
//        return listKelas3.getSelectedValue();
//    }
//
//    public String getSelecttMatkul() {
//        return listMatkul.getSelectedValue();
//    }

    public JButton getBtHapusList1() {
        return btHapusList;
    }

    public JButton getBtTambahList1() {
        return btTambahList;
    }

    
    
    
//    public void setListKelas1(ArrayList<String> List){
//        this.listKelas1.setModel(new DefaultComboBoxModel(List.toArray()));
//    }
//    
//    public void setListKelas2(ArrayList<String> List){
//        this.listKelas2.setModel(new DefaultComboBoxModel(List.toArray()));
//    }
    
    public void setSelected(ArrayList<String> List){
        this.listSelected.setModel(new DefaultComboBoxModel(List.toArray()));
    }
    
    public void setSelected1(ArrayList<String> List){
        this.listSelected1.setModel(new DefaultComboBoxModel(List.toArray()));
    }

    public JComboBox<String> getCbKelas() {
        return cbKelas;
    }

    public JComboBox<String> getCbKelas2() {
        return cbKelas2;
    }
    
//    public void setMatkul(ArrayList<String> List){
//        this.listMatkul.setModel(new DefaultComboBoxModel(List.toArray()));
//    }
//    

    public JList<String> getListSelected() {
        return listSelected;
    }

    public JList<String> getListSelected1() {
        return listSelected1;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
//    public JList<String> getListKelas1() {
//        return listKelas1;
//    }
////bla.setListData
//    public JList<String> getListKelas2() {
//        return listKelas2;
//    }

    public JList<String> getListKelas3() {
        return listSelected;
    }

//    public JList<String> getListMatkul() {
//        return listMatkul;
//    }
    
    

    public String getTfKelas() {
        return tfKelas.getText();
    }


//    public JTextField getTfMatkul() {
//        return tfMatkul;
//    }

    public String getTfNamaTugas() {
        return tfNamaTugas.getText();
    }

    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddKelas;
    private javax.swing.JButton btAddTugas;
    private javax.swing.JButton btHapusList;
    private javax.swing.JButton btHapusList1;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btTambahList;
    private javax.swing.JButton btTambahList1;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JComboBox<String> cbKelas2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JComboBox<String> listMatkul;
    private javax.swing.JList<String> listSelected;
    private javax.swing.JList<String> listSelected1;
    private javax.swing.JTabbedPane menuDosenl;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JTextField tfKelas;
    private javax.swing.JTextField tfNamaTugas;
    // End of variables declaration//GEN-END:variables
}
